baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo-profile"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2

params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Claudia Villena"
  namecolor: ffc107
  profession: "Political scientist"
  github: "https://github.com/ClaudiaVillena27"
  linkedin: "https://www.linkedin.com/in/claudiavillenatagle/"
  facebook: "https://www.facebook.com/claudia.villena.52"


  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "Hello! My name is Claudia Villena. I graduated in Political Science and Government from the Pontificia Universidad Catolica del Peru (PUCP). I got an outstanding mention in my thesis investigation about corruption in public procurement."
  descripe_l2_person: "I am currently working as an academic assistant in the PUCP, in the specialization of Political Science. I am engaged in teaching activities as a Teachers's assistant in Political Economics at the same department. Prior to joining the PUCP, I worked as a project assistant in the Municipality of Miraflores, in the department of Urban Mobility and as Research Assistant, in the Jurado Nacional de Elecciones (JNE). By the time, i have been working on developing my abilities in Data Science and quantitative methods of research. My goal is to develop my professional career in corruption and security field applying my analytical skills."
  skills:
    - name: SPSS
      percentage: 90
    - name: R Studio
      percentage: 85
    - name: Python
      percentage: 50
    - name: Google Data Studio
      percentage: 90

  # Experience
  disable_experience: false
  experience:
    - company: "Pontificia Universidad Católica del Perú"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Academic Assistant"
      startdate: Jul 2021
      enddate: present
      featuredpoints:
        - point: Attend the academic affairs of the Political Science Specialty, Social Science.
    - company: "DNEF- JNE"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Research Assistant for the Visualization of data"
      startdate: Mar 2021
      enddate: Jun 2021
      featuredpoints:
        - point: Assistance in statistical analysis and visualization of data from research projects.
        - point: Assistance in the application of surveys and collection of quantitative and qualitative information.
        - point: Data analysis in R
    - company: "Municipalidad de Miraflores"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Project Assistant"
      startdate: Jan 2020
      enddate: Feb 2021
      featuredpoints:
        - point: Support in the elaboration of the Strategic Plan of the Municipality of Miraflores, departament of Urban Mobility.
        - point: Data analysis in R.
        - point: Development of visualization boards in Google DataStudio
  # Education
  disable_education: false
  education:
    - degree: "B.tech"
      branch: "Information Technology"
      university: "Example university"
      startedyear: "2013"
      graduation: "2018"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "example@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
